# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase
from PyQt5.QtCore import QTime, QDate


class Ui_MachineTest(object):
    def setupUi(self, MachineTest):
        MachineTest.setObjectName("MachineTest")
        MachineTest.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MachineTest)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.timeEdit.setFont(font)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setFrame(False)
        self.timeEdit.setReadOnly(False)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setKeyboardTracking(True)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        self.labelFormat = QtWidgets.QLabel(self.centralwidget)
        self.labelFormat.setText("")
        self.labelFormat.setObjectName("labelFormat")
        self.horizontalLayout_2.addWidget(self.labelFormat)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setFrame(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setObjectName("checkBox1")
        self.verticalLayout.addWidget(self.checkBox1)
        self.checkBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox2.setObjectName("checkBox2")
        self.verticalLayout.addWidget(self.checkBox2)
        self.checkBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox3.setObjectName("checkBox3")
        self.verticalLayout.addWidget(self.checkBox3)
        self.checkBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox4.setObjectName("checkBox4")
        self.verticalLayout.addWidget(self.checkBox4)
        self.checkBox5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox5.setObjectName("checkBox5")
        self.verticalLayout.addWidget(self.checkBox5)
        self.checkBox6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox6.setObjectName("checkBox6")
        self.verticalLayout.addWidget(self.checkBox6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.labelConnection = QtWidgets.QLabel(self.centralwidget)
        self.labelConnection.setObjectName("labelConnection")
        self.verticalLayout_2.addWidget(self.labelConnection)
        MachineTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MachineTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MachineTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MachineTest)
        self.statusbar.setObjectName("statusbar")
        MachineTest.setStatusBar(self.statusbar)

        self.retranslateUi(MachineTest)
        QtCore.QMetaObject.connectSlotsByName(MachineTest)
        self.dbConnection()

        self._12hour()

        self.dateEdit.setDate(QDate.currentDate())

        self.btnSave.clicked.connect(self.save)
        self.comboBox.currentIndexChanged.connect(self.updateHour)
        


    def dbConnection(self):
        self.labelConnection.setText('Connecting to database...')
        db = QSqlDatabase.addDatabase('QMYSQL')
        db.setHostName("sql2.freemysqlhosting.net")
        db.setDatabaseName("sql2365946")
        db.setUserName("sql2365946")
        db.setPassword("mypass")
        db.setPort(3306)
        if db.open():
            self.labelConnection.setText("<font color='green'><b>Connected</b></font>")
        else:
            self.labelConnection.setText("<font color='red'><b>Failed</b></font>")
    def save(self):
        self.labelConnection.setText('Connected')
    def _12hour(self):
        self.timeEdit.setDisplayFormat('hh:mm A')
        self.timeEdit.setTime(QTime.currentTime())
    def _24hour(self):
        self.timeEdit.setDisplayFormat('HH:mm')
        self.timeEdit.setTime(QTime.currentTime())
    def updateHour(self):
        if self.comboBox.currentIndex()==0:
            self._12hour()
        else:
            self._24hour()

    def retranslateUi(self, MachineTest):
        _translate = QtCore.QCoreApplication.translate
        MachineTest.setWindowTitle(_translate("MachineTest", "MachineTest"))
        self.timeEdit.setDisplayFormat(_translate("MachineTest", "HH:mm"))
        self.comboBox.setItemText(0, _translate("MachineTest", "12-hour"))
        self.comboBox.setItemText(1, _translate("MachineTest", "24-hour"))
        self.checkBox1.setText(_translate("MachineTest", "CheckBox"))
        self.checkBox2.setText(_translate("MachineTest", "CheckBox"))
        self.checkBox3.setText(_translate("MachineTest", "CheckBox"))
        self.checkBox4.setText(_translate("MachineTest", "CheckBox"))
        self.checkBox5.setText(_translate("MachineTest", "CheckBox"))
        self.checkBox6.setText(_translate("MachineTest", "CheckBox"))
        self.btnSave.setText(_translate("MachineTest", "Save"))
        self.btnCancel.setText(_translate("MachineTest", "Cancel"))
        self.labelConnection.setText(_translate("MachineTest", "l"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MachineTest = QtWidgets.QMainWindow()
    ui = Ui_MachineTest()
    ui.setupUi(MachineTest)
    MachineTest.show()
    sys.exit(app.exec_())
